"""Typeset six finished Pin examples from unchanged approved photography."""
from pathlib import Path
import base64,html,json,hashlib
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'src/assets/wys/examples'
def uri(p,m='image/png'):return 'data:'+m+';base64,'+base64.b64encode(p.read_bytes()).decode()
news=uri(ROOT/'node_modules/@fontsource/newsreader/files/newsreader-latin-600-normal.woff2','font/woff2')
inter=uri(ROOT/'node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2','font/woff2')
flower='<svg viewBox="0 0 120 120"><g fill="#fffafd" stroke="#eaa6c5">'+''.join(f'<ellipse cx="60" cy="27" rx="14" ry="25" transform="rotate({a} 60 60)"/>' for a in range(0,360,60))+'</g><circle cx="60" cy="60" r="16" fill="#ff8ac2" stroke="#d62e73"/><ellipse cx="55" cy="54" rx="7" ry="4" fill="#ffe6f2"/></svg>'
records=[]
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 for slug,name,theme in [('pretty-wicked-entryway','Pretty Wicked','entryway'),('ghoul-fuel-coffee-bar','Ghoul Fuel','coffee bar')]:
  headlines=['Pink Halloween<br>'+theme,('Style a playful<br>pink welcome' if theme=='entryway' else 'A little haunt for<br>your coffee corner'),('Your cutest<br>Halloween welcome' if theme=='entryway' else 'Your cutest<br>coffee moment')]
  for n,role in enumerate(['basic','styled','lifestyle']):
   source=ROOT/'src/lifestyle'/f'{slug}-{role}.png'
   css=f'''@font-face{{font-family:Newsreader;src:url({news});font-weight:600}}@font-face{{font-family:Inter;src:url({inter});font-weight:400}}*{{box-sizing:border-box}}body{{margin:0;width:1000px;height:1500px;padding:38px;color:#1a1417;font-family:Inter;background:#ffe0ee;display:grid;grid-template-rows:32px 220px minmax(0,1fr) 70px;gap:20px;position:relative}}body:before{{content:'';position:absolute;inset:15px;border:2px solid #fff8fc;pointer-events:none}}.brand{{text-align:center;font:400 20px/1.5 Inter;letter-spacing:4px;text-transform:uppercase}}header{{text-align:center;position:relative;display:grid;place-content:center}}h1{{font:600 86px/1.05 Newsreader;margin:0;color:#b8245f}}.sub{{font:400 25px/1.5 Inter;letter-spacing:1px;margin-top:15px}}.photo{{position:relative;padding:20px;display:flex;align-items:center;justify-content:center;background:#fff8fc;border:7px double #d98ab2;box-shadow:0 18px 25px #b8245f20;min-height:0}}img{{display:block;width:100%;height:100%;object-fit:contain}}.flower{{position:absolute;width:120px;height:120px;bottom:-26px;left:18px;filter:drop-shadow(0 7px 5px #b8245f20)}}footer{{display:flex;align-items:center;justify-content:space-between;gap:15px;font:400 20px/1.5 Inter}}footer b{{font-weight:400;color:#b8245f;font-size:24px}}.badge{{position:absolute;right:10px;top:18px;background:#fff8fc;border:5px double #d88db2;border-radius:50%;width:95px;height:95px;display:grid;place-content:center;font:400 18px/1.3 Inter;transform:rotate(10deg)}}.design-0{{background:repeating-linear-gradient(90deg,#ffdeed 0,#ffdeed 20px,#ffedf5 20px,#ffedf5 40px)}}.design-0 header{{background:#fff5fa;border:2px solid #e29bbc;border-radius:8px 60px 8px 8px}}.design-0 h1{{font-size:80px}}.design-1{{background:#eadcf9;grid-template-rows:32px minmax(0,1fr) 230px 70px}}.design-1 header{{grid-row:3;background:#fff8fc;border:5px double #b99bd5;border-radius:8px 60px 8px 8px}}.design-1 .photo{{grid-row:2;background:#f8f1ff;border-color:#b99bd5;border-radius:120px 120px 8px 8px}}.design-1 .flower{{left:auto;right:-15px;bottom:20px}}.design-1 h1{{font-size:78px}}.design-2{{background:radial-gradient(ellipse at 30% 20%,#fff2fa,#ffc4df);grid-template-rows:32px 210px minmax(0,1fr) 70px}}.design-2 .photo{{background:#ffd9eb;border:4px solid #fff8fc;outline:2px solid #dd98bc;outline-offset:8px;transform:rotate(2deg);margin:0 42px;border-radius:70px 70px 8px 8px}}.design-2 h1{{font-size:82px}}.design-2 .flower{{left:-35px;bottom:30px}}'''
   badge='<span class="badge">5<br>FINDS</span>' if n==0 else ''
   markup=f'<!doctype html><html lang="en"><style>{css}</style><body class="design-{n}"><div class="brand">The Digital Income Edit™</div><header><h1>{headlines[n]}</h1><div class="sub">{html.escape(name)} · Pink Halloween {theme}</div>{badge}</header><div class="photo"><img src="{uri(source)}"><div class="flower">{flower}</div></div><footer><b>Explore the styling story →</b><span>AI styling inspiration</span></footer></body></html>'
   page=b.new_page(viewport={'width':1000,'height':1500},device_scale_factor=1);page.set_content(markup);page.evaluate('document.fonts.ready');page.locator('img').evaluate('(e)=>e.decode()');assert page.evaluate('document.documentElement.scrollHeight===1500');target=OUT/f'{slug}-pin-{n+1}.png';page.screenshot(path=str(target));page.close()
   records.append({'file':target.name,'source':source.name,'sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'width':1000,'height':1500,'method':'Deterministic native HTML typesetting; approved original source photo unchanged; finished website example Pin','photoRole':role,'overlay':headlines[n].replace('<br>',' ')})
 b.close()
p=ROOT/'docs/design/WYS_EXAMPLE_GRAPHICS_2026-10-08.json';previous=json.loads(p.read_text());p.write_text(json.dumps([r for r in previous if '-pin-' not in r['file']]+records,indent=2));print('Six finished 1000 × 1500 Pins created; original photos unchanged')
