import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require('/opt/node-tools/node_modules/playwright');
const out = process.argv[2];
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:720,height:960},deviceScaleFactor:1.5});
await p.goto('http://localhost:4321/_wysguide.html',{waitUntil:'networkidle'}); await p.evaluate(()=>document.fonts.ready);
await p.addStyleTag({content:'.e-reveal,.e-unveil{opacity:1!important;transform:none!important;clip-path:none!important}'});
await p.waitForTimeout(800);
const qa = await p.evaluate(()=>[...document.querySelectorAll('.gpage')].map(g=>{const gb=g.querySelector('.gbody');return g.id+' overflow='+(gb.scrollHeight-gb.clientHeight)+' docW='+document.documentElement.scrollWidth}));
console.log(qa.join('\n'));
const pages = await p.$$('.gpage');
for (let i=0;i<pages.length;i++) await pages[i].screenshot({path:`${out}/wys-preview-guide-p${String(i+1).padStart(2,'0')}.png`});
await p.pdf({path:`${out}/WYS-Free-Preview-Guide.pdf`,width:'720px',height:'960px',printBackground:true,preferCSSPageSize:true});
await b.close();
